### PR TITLE
TAMAYA-350 - Do not provide null as "null" string

### PR DESCRIPTION
**Pull request by alexsuter**

### CODE REVIEW

**Comment by alexsuter** [comment]
Meanwhile I think it would better, to not provide null values in the properties at all.

**Comment by ottlinger** [comment]
Please add a test case to avoid regressions. Thanks

**Comment by alexsuter** [comment]
Test added.

**Comment by atsticks** [comment]
The corresponding change has been done in the code, see the current snippet, so I will close this request:
```
if (en.getValue() == null) {
         dataNode.setValue(en.getKey(), null);
}else {
        dataNode.setValue(en.getKey(), String.valueOf(en.getValue()));
}
```

**Pull request closed without merging**
