### PR TITLE
TAMAYA-394 sonar errors

### PR DESCRIPTION
**Pull request by peculater**
This PR is to see about fixing some of the issues pointed out by SonarCloud.  I focused on bugs and security vulnerabilities.  The largest set of changes were in the distributed config example.  The most meaningful changes were in the etcd module, where I ended up refactoring some of the queries to work on a more modern (0.4 from 2014 to -> 3.3 from 2019) version of etcd.

### CODE REVIEW

**Comment by peculater** [comment]
Good news, SonarCloud reports 0 bugs and 0 vulnerabilities in this branch.

**Comment by peculater** [comment]
I'm going to go ahead and merge that, despite the code coverage sitting at 0% (?) and the code duplication warning.

**Comment by ottlinger** [comment]
@peculater maybe lombok could have been of use in the example projects to have slimmer POJOs.

**Comment by peculater** [comment]
It absolutely could have been used instead of generating the code in the IDE.  I'm not real familiar with lombok, other than seeing a presentation on it at a meetup a few months ago.  I wouldn't be opposed to switching to using something like that, as long as we did so consistently throughout the project.

**Comment by ottlinger** [comment]
@peculater I would not hesitate to use Lombok in the example projects ... maybe this makes the quality build green again as it raises the coverage bar ;)

**Pull request merged**
